sonar.projectKey=Marius-Ar_suunto-api-wrapper
sonar.organization=marius-ar
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=src/**/*.test.ts,src/**/__screenshots__/**,dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
