export {
  HttpClient,
  HttpError,
  type HttpClientOptions,
  type HttpResponse,
  type RequestOptions,
  type RequestContext,
  type RequestBody,
  type Query,
} from "./http/index.js";

export { generateXtotp, secondsUntilRollover } from "./otp/index.js";

export {
  login,
  sessionTokenFrom,
  SPORTS_TRACKER_API,
  DEFAULT_USER_AGENT,
  type LoginOptions,
  type LoginResponse,
} from "./auth/index.js";

export {
  SuuntoActivityType,
  WorkoutsResource,
  type GetWorkoutsParams,
  type GetOwnWorkoutsParams,
  type GetWorkoutsWithinParams,
  type WorkoutsResponse,
  type WorkoutsWithinResponse,
  type WorkoutsWithinItem,
  type WorkoutStatsResponse,
  type WorkoutStats,
  type WorkoutStatsEntry,
  type Workout,
  type Position,
  type Cadence,
  type HrData,
  type Gear,
  type HeartRateRecovery,
  type TssEntry,
  type Rankings,
  type RouteRanking,
  type ClientCalculatedAchievements,
  type CumulativeAchievement,
  type PersonalBestAchievement,
  type ActivityCounts,
  type WorkoutComment,
  type WorkoutReaction,
  type IntensityZone,
  type IntensityZones,
  type WorkoutExtension,
  type FitnessExtension,
  type IntensityExtension,
  type SummaryExtension,
  type WeatherExtension,
  type SwimmingHeaderExtension,
} from "./workouts/index.js";

export {
  UsersResource,
  type UserProfile,
  type UserProfileResponse,
  type SearchUser,
  type UserSearchResult,
  type UserSearchResponse,
} from "./users/index.js";

export {
  GearResource,
  type GetLatestGearParams,
  type GearSummary,
  type GearResponse,
} from "./gear/index.js";

export {
  WellnessResource,
  SPORTS_TRACKER_247_API,
  type ExportParams,
  type ExportEntry,
  type SleepSummaryData,
  type SleepStage,
  type SleepStageData,
  type RecoveryData,
  type ActivityData,
  type SleepSummary,
  type SleepStageInterval,
  type RecoveryEntry,
  type ActivityEntry,
  type SleepExportResponse,
  type SleepStagesExportResponse,
  type RecoveryExportResponse,
  type ActivityExportResponse,
} from "./wellness/index.js";

export {
  GuidesResource,
  // fluent builder
  guide,
  GuideBuilder,
  GUIDE_DESCRIPTION_MAX_LENGTH,
  GUIDE_SHORT_DESCRIPTION_MAX_LENGTH,
  StepsBuilder,
  PhaseBuilder,
  GUIDE_STEP_TITLE_MAX_LENGTH,
  GUIDE_TEXT_FIELD_VALUE_MAX_LENGTH,
  // condition helpers
  or,
  and,
  stepDuration,
  stepDistance,
  duration,
  distance,
  manualLap,
  location,
  // field helpers
  hr,
  pace,
  power,
  cadence,
  speed,
  targetHr,
  targetPace,
  targetPower,
  targetCadence,
  targetSpeed,
  targetHrZone,
  targetPaceZone,
  targetPowerZone,
  targetFromZone,
  stepDurationCountdown,
  stepDistanceCountdown,
  text,
  variable,
  rawField,
  // types
  type GuideContent,
  type GuideDefinition,
  type GuideListResponse,
  type GuideUploadResponse,
  type Guide,
  type GuideStep,
  type GuideFieldsStep,
  type GuideNotificationStep,
  type GuideRepeatStep,
  type GuideCondition,
  type GuideConditionAnd,
  type GuideConditionOr,
  type GuideConditionDistance,
  type GuideConditionDuration,
  type GuideConditionStepDistance,
  type GuideConditionStepDuration,
  type GuideConditionLocation,
  type GuideConditionManualLap,
  type GuideField,
  type GuideFieldVariable,
  type GuideFieldVariableType,
  type GuideFieldTargetRange,
  type GuideFieldTargetRangeType,
  type GuideFieldTargetFromZone,
  type GuideFieldTargetFromZoneType,
  type GuideFieldZoneSelector,
  type GuideFieldZoneSelectorType,
  type GuideFieldCountdown,
  type GuideFieldCountdownType,
  type GuideFieldText,
  type GuideAlert,
  type GuideCountdown,
  type GuideLap,
  type GuideNotification,
  type GuideTransition,
  type GuideStepOptions,
  type GuideStepExtensions,
  type SuuntoStepExtensions,
  type GuideSequenceExtensions,
  type SuuntoGuideSequenceExtensions,
  type GuideRaceParameters,
  type GuidePhase,
  type GuideUsage,
  type GuideWorkoutPlanType,
  type GuideUnitSystem,
  type GuideFieldVariableAggregate,
  type GuideFieldVariableWindow,
} from "./guides/index.js";

export { SuuntoClient, type SuuntoClientOptions } from "./client.js";
